name: Fuzzing

on:
  schedule:
    # Run fuzzing daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libcjson-dev
    
    - name: Setup build
      run: make setup
    
    - name: Build
      run: make build
    
    - name: Run fuzzing
      run: make fuzz-long
      timeout-minutes: 30
